# Generated by Django 4.2.2 on 2023-06-19 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100)),
                ('date_of_birth', models.DateField(default=None, null=True, verbose_name='Date of Birth')),
                ('address1', models.CharField(default=None, max_length=1000, null=True, verbose_name='Address line 1')),
                ('address2', models.CharField(default=None, max_length=1000, null=True, verbose_name='Address line 2')),
                ('zip_code', models.CharField(default=None, max_length=12, null=True, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(default=None, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(default=None, max_length=100, null=True, verbose_name='State')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
