# Generated by Django 4.2.2 on 2023-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_user_address1_user_address2_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=None, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default=None, max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
    ]
