# Generated by Django 4.2.2 on 2023-06-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='hopsital_name',
            new_name='hospital_name',
        ),
    ]
