# Generated by Django 4.2.2 on 2023-06-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_rename_hopsital_name_bill_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='eob_image_url',
            field=models.URLField(blank=True, default=None, max_length=500, verbose_name='EOB Image URL'),
        ),
    ]
